---
title: "Análise precatórios"
format: markdown_github
---

## Quais dados queremos analisar?

Estamos interessados somente em precatórios na esfera Federal, decorrentes de discussões relacionadas a PIS/COFINS.

## Onde estão os dados?

Teoricamente, se um processo transitou em julgado contra a União, ele se torna um precatório. Portanto, para encontrar todos os precatórios temos de encontrar todos os processos transitados em julgados, em qualquer instância (nas varas, no tribunal, nos tribunais superiores) e verificar se a decisão vai contra a União.

Uma análise desse tipo é inviável. Uma alternativa é estudar as consultas de jurisprudência dos TRFs, buscando informações sobre trânsito em julgado.

Para isso, uma fonte útil de informações é a [jurisprudência unificada do TRF](https://www2.cjf.jus.br/jurisprudencia/unificada/), que fornece uma consulta em todos os tribunais. A consulta tem problemas, claro, mas existe e está atualizada.

As tarefas aqui então seriam

1. Listar os processos usando algum critério de busca razoável
2. Filtrar os processos com
    - decisão (parcialmente/totalmente) favorável e apelante diferente de União
    - decisão desfavorável e apelante União
3. Pesquisar os casos filtrados no Datajud
4. Filtrar processos com
    - trânsito em julgado
    - existência de movimentação de precatório (se possível)
5. Analisar as decisões que sobrarem
    
A etapa 2 pode ser suprimida se o acesso ao Datajud for rápido/fácil

### Impossibilidade da consulta nos sites

Os sites dos TRFs apresentam tanto consultas via PJe (casos mais novos) quanto consultas via sistemas próprios (casos mais antigos). Os sistemas são todos difíceis de acessar e as informações não ajudam muito. A única forma de obter os resultados desejados é mesmo com o Datajud.

### Análise de amostra

Como o interesse é analisar os fundamentos utilizados, uma alternativa é realizar uma pesquisa jurimétrica por amostragem. Nesse tipo de pesquisa, os casos são lidos por pesquisadores, que preenchem um formulário de classificação que compõe uma base de dados. Após a classificação, a base de dados é analisada e os resultados obtidos.


## Links úteis

[Jurisprudência unificada TRF](https://www2.cjf.jus.br/jurisprudencia/unificada/)

[Link de precatórios do STJ](https://www.stj.jus.br/sites/portalp/Processos/precatorios)

[Consulta precatórios TRF3](https://web.trf3.jus.br/consultas/Internet/ConsultaReqPag) (consegui acessar pelo CPF de uma pessoa da família)
