on:
  workflow_dispatch:
  schedule:
  - cron: '00 07 18 * *'

jobs:
  update-sheets:
    name: Atualiza o sheets com processos do TRF4
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    steps:
      - name: Checkout from repository
        uses: actions/checkout@v2

      - name: Config R and Rscript
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::lubridate
            any::stringr
            any::dplyr
            any::tibble
            any::readr
            any::purrr
            any::glue
            any::fs
            any::googlesheets4
            any::abjutils

      - name: Install remotes, and the updated package
        run: |
          remotes::install_github("terranova/lex", force = TRUE)
          remotes::install_github("abjur/obsutils", force = TRUE)
        shell: Rscript {0}

    - name: Use script
      run: Rscript inst/update-sheets-fz.R
